name: Collage-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8==3.7.9
        flake8 .
    - name: Test with pytest
      run: |
        pip install pytest==5.4.1
        pytest -v
    - name: Packaging project
      run: |
        pip install setuptools==46.0.0 wheel==0.34.2
        python setup.py sdist bdist_wheel
        pip install dist/collage-0.0.1-py3-none-any.whl
    - name: Upload distribution archives
      uses: actions/upload-artifact@master
      with:
        name: distribution-archives
        path: dist
        if: always()
